import type { Metadata } from 'next'

import { Roboto } from 'next/font/google'

import Provider from './provider'

import './globals.css'

const roboto = Roboto({
  style: ['normal'],
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Next Stock App',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
